version: 2

jobs:
  # The build job
  build:
    working_directory: ~/flingo
    docker:
      - image: cimg/node:16.13

    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Install project dependencies
      - run:
          name: Install local dependencies
          env:
              # avoid downloading and unzipping Cypress binary
              # which saves time - we do not plan to run Cypress tests
              # in this lint workflow, see
              # https://on.cypress.io/installing
              CYPRESS_INSTALL_BINARY: 0
          command: npm ci

      - run:
          name: Install local dependencies
          command: npx nx run flingo:build:dev

  # The test job
  test:
    working_directory: ~/flingo
    docker:
      - image: cimg/node:16.15-browsers

    steps:
      # Checkout the code from the branch into the working_directory
      - checkout

      # Install project dependencies
      - run:
          name: Install testing dependencies
          command: npm ci

      # Lint the source code
      - run:
          name: Linting
          command: npm run affected:lint
      # Test the source code
      - run:
          name: Unit testing
          command: npm run affected:test

      - run:
          name: 2e2 testing
          command: npm run affected:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
